#! /bin/sh

# Restore wallpaper
feh --no-fehbg --bg-scale "$HOME/.config/bspwm/wallpaper.jpg"

bspc monitor ${monitor} -n "$name" -d '1' '2' '3' '4' '5' '6' '7'

bspc config external_rules_command "$HOME/.config/bspwm/scripts/spotify.sh"

bspc config border_width         2
bspc config top_padding        46
bspc config window_gap           10
bspc config split_ratio          0.50

bspc config focused_border_color "#7aa2f7"
bspc config normal_border_color "#32344a"
bspc config active_border_color "#444b6a"
bspc config pointer_motion_interval 6

bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true

# fix pointer
xsetroot -cursor_name left_ptr

bspc rule -a 'Alacritty:float' state=floating y

# workspace 1 (Terminals)
declare -a terminal=("Alacritty:normal" Xfce4-terminal)
for i in ${terminal[@]}; do
    bspc rule -a $i desktop='^1' follow=on focus=on; done

# workspace 2 (Internet Browser)
declare -a web=(firefox librewolf Brave-browser)
for i in ${web[@]}; do
    bspc rule -a $i desktop='^2' follow=on focus=on; done

# workspace 3 (Files)
declare -a filem=(Thunar Pcmanfm qBittorrent)
for i in ${filem[@]}; do
    bspc rule -a $i desktop='^3' follow=on focus=on; done

# workspace 4 (Text Editor)
declare -a office=(Code Geany)
for i in ${office[@]}; do
    bspc rule -a $i desktop='^4' follow=on focus=on; done

# workspace 5 (Media)
declare -a media=(discord )
for i in ${media[@]}; do
    bspc rule -a $i desktop='^5' follow=on focus=on; done

# workspace 5 (Media)
declare -a music=(Cider spotify Spotify )
for i in ${music[@]}; do
    bspc rule -a $i desktop='^6' follow=on focus=on; done

# workspace 7 (Settings)
declare -a settings=(Steam steam \
Xfce4-settings-manager steam)
for i in ${settings[@]}; do
    bspc rule -a $i desktop='^7' follow=on focus=on; done

# floating windows
declare -a floats=(Alafloat Lxappearance Arandr Cider \
Viewnior Pcmanfm feh Nm-connection-editor Matplotlib Yad discord obs Steam steam Lazap lazap electron minecraft-launcher photoshop.exe)
for i in ${floats[@]}; do
  bspc rule -a $i state=floating center=true follow=on focus=on; done

## Autostart
exec systemctl --user import-environment &

# Kill if already running
killall -9 flameshot eww

eww open bar

# polkit agent
if [[ ! `pidof polkit-gnome-authentication-agent-1` ]]; then
    /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
fi

picom --config $HOME/.config/bspwm/picom.conf &

sxhkd &
flameshot
