#! /bin/sh

# Restore wallpaper
bash $HOME/.config/bspwm/.fehbg

# running polybar
$HOME/.config/bspwm/polybar/launch.sh 

#Fix mouse
xsetroot -cursor_name left_ptr

# workspaces load
workspaces() {
	name=1
	for monitor in `bspc query -M`; do
		bspc monitor ${monitor} -n "$name" -d '' '' '' '' '' '' ''
		let name++
	done
}
workspaces

# bspwm window config
bspc config border_width 0
bspc config window_gap 30
bspc config bottom_padding 5
bspc config left_padding 6
bspc config right_padding 6

# workspace 1 (Terminals)
declare -a terminal=()
for i in ${terminal[@]}; do
    bspc rule -a $i desktop='^1' follow=on focus=on; done
    
# workspace 2 (Internet Browser)
declare -a web=(firefox)
for i in ${web[@]}; do
    bspc rule -a $i desktop='^2' follow=on focus=on; done

# workspace 3 (Files)
declare -a filem=(Thunar Pcmanfm qBittorrent)
for i in ${filem[@]}; do
    bspc rule -a $i desktop='^3' follow=on focus=on; done

# workspace 4 (Text Editor)
declare -a office=(Code Geany)
for i in ${office[@]}; do
    bspc rule -a $i desktop='^4' follow=on focus=on; done

# workspace 5 (Chat)
declare -a media=(discord)
for i in ${media[@]}; do
    bspc rule -a $i desktop='^5' follow=on focus=on; done

# workspace 6 (Music)
declare -a music=(spotify Spotify)
for i in ${music[@]}; do
    bspc rule -a $i desktop='^6' follow=on focus=on; done

# workspace 7 (Games)
declare -a settings=(lutris steam Steam)
for i in ${settings[@]}; do
    bspc rule -a $i desktop='^7' follow=on focus=on; done

# floating windows
declare -a floats=(Alafloat Lxappearance Arandr \
Viewnior Pcmanfm feh Nm-connection-editor Matplotlib Yad)
for i in ${floats[@]}; do
  bspc rule -a $i state=floating follow=on focus=on; done

# Kill if already running
killall -9 picom sxhkd xbindkeys

# Start keybinding daemon
sxhkd &

# Enable numlock
numlockx on

# Start compositor
picom --experimental-backends --config $HOME/.config/bspwm/picom.conf &

#Set RGB colors for PC
/home/porya/.config/OpenRGB/openrgb -p default.orp